apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::935041970526:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-W1HF5Z0U855U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::935041970526:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-16T08:01:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2370"
  uid: 60f89ef9-2ee3-4f5a-b587-19dd28d385c2
