apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::109797950479:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DNEFPT4DNGC4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-14T08:03:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1629"
  uid: 39a7bd27-738b-4e87-83e5-cffa51c29b01
